### PR TITLE
Update contributors.js

### PR DESCRIPTION
**Pull request by naitiklovestech**
Added my details in the contributors file for my first open source contribution

### CODE REVIEW

**Comment by AKACHI-4** [comment]
hey @Lucifer-Overridden .. happy for ur first contribution .. kindly add/update ur details in `Contributors.md` too.. 

Thank you ❤

**Comment by naitiklovestech** [comment]
@AKACHI-4, I have done the necessary changes

**Comment by AKACHI-4** [comment]
Thanks @Lucifer-Overridden for Contribution .. ❤

Keep contributing nd keep doing amazing in ur open source journey ...

**Comment by AKACHI-4** [comment]
Also make sure to check `first-contribution site` for ur contribution card.. 

Happy Contribution Ahead 🥳

**Pull request merged**
